### ISSUE TITLE
I try to run it on frey faces after 40 epoc I get the following error

### ISSUE THREAD

**Issue by ehfo0** [y0ast/Variational-Autoencoder#11]
Please help me fix it.
[instantiating model
iterating

'''''
[Epoch 40 finished. LB: 576.144198455, time: 0.140044927597
Traceback (most recent call last):
  File "/home/hoda/Downloads/Variational-Autoencoder-1-master/run.py", line 66, in <module>
    valid_LB = model.likelihood(x_valid)
  File "/home/hoda/anaconda2/lib/python2.7/site-packages/theano/compile/function_module.py", line 795, in __call__
    allow_downcast=s.allow_downcast)
  File "/home/hoda/anaconda2/lib/python2.7/site-packages/theano/tensor/type.py", line 140, in filter
    raise TypeError(err_msg)
TypeError: Bad input argument to theano function with name "/home/hoda/Downloads/Variational-Autoencoder-1-master/VAE.py:158" at index 0 (0-based).  
Backtrace when that variable is created:

  File "/home/hoda/Downloads/Variational-Autoencoder-1-master/run.py", line 34, in <module>
    model = VAE(continuous, hu_encoder, hu_decoder, n_latent, x_train)
  File "/home/hoda/Downloads/Variational-Autoencoder-1-master/VAE.py", line 84, in __init__
    self.update, self.likelihood, self.encode, self.decode = self.create_gradientfunctions(x_train)
  File "/home/hoda/Downloads/Variational-Autoencoder-1-master/VAE.py", line 128, in create_gradientfunctions
    x = T.matrix("x")
TensorType(float32, matrix) cannot store a value of dtype float64 without risking loss of precision. If you do not mind this loss, you can: 1) explicitly cast your data to float32, or 2) set "allow_input_downcast=True" when calling "function". Value: "array([[ 0.65234375,  0.734375  ,  0.79296875, ...,  0.4609375 ,
         0.3984375 ,  0.37890625],
       [ 0.66796875,  0.74609375,  0.625     , ...,  0.4921875 ,
         0.44140625,  0.41015625],
       [ 0.6875    ,  0.73828125,  0.6953125 , ...,  0.453125  ,
         0.390625  ,  0.37109375],
       ..., 
       [ 0.6875    ,  0.671875  ,  0.39453125, ...,  0.56640625,
         0.2734375 ,  0.2890625 ],
       [ 0.71484375,  0.6640625 ,  0.48828125, ...,  0.47265625,
         0.34765625,  0.30859375],
       [ 0.7734375 ,  0.65234375,  0.5703125 , ...,  0.3515625 ,
         0.30859375,  0.28125   ]])"
](url)](url)

PS: thnx for sharing ur code:

**Comment by y0ast** [comment]
Sorry that was a mistake on my side. Fixed.
