### ISSUE TITLE
Continuous = True causes error

### ISSUE THREAD

**Issue by PFWhite** [y0ast/Variational-Autoencoder#9]
After changing the continuous variable I encountered the following error after doing a python run.py
```
Loading Freyface data
instantiating model
Restarting from earlier saved parameters!
Traceback (most recent call last):
  File "run.py", line 43, in <module>
    model.load_parameters(path)
  File "/home/patrick/.../Variational-Autoencoder/VAE.py", line 184, in load_parameters
    self.params[name].set_value(p_list[name].astype(theano.config.floatX))
KeyError: 'W_hx'
```

**Comment by y0ast** [comment]
Hi! I think you are trying to restart training a continuous model from binary model parameters.

I think if you delete the params.pkl file and start training again it should be fine :)

**Comment by SlothFox** [comment]
Hi,
even when deleting the params.pkl I get the following error when setting continuous = True:
```javascript
  File "/home/alexander/anaconda3/lib/python3.6/site-packages/theano/gof/fg.py", line 397, 
in __import__    raise MissingInputError(error_msg, variable=r)

MissingInputError: Input 0 of the graph (indices start from 0), used to compute dot(x, W_xh),
was not provided and not given a value. Use the Theano flag exception_verbosity='high', for
more information on this error. 
```
Any idea what could cause the error?

Tanks

Alexander
